name: Unlighthouse Audit

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  perf-check:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Unlighthouse & Utils
        run: pnpm i -g @unlighthouse/cli puppeteer start-server-and-test

      - name: Build docs
        run: pnpm run docs:build

      - name: Run Unlighthouse
        run: start-server-and-test 'pnpm run docs:preview' http://localhost:4173 'unlighthouse-ci --site http://localhost:4173 --build-static --budget 75'

      - name: Upload Report
        uses: actions/upload-artifact@v5
        with:
          name: unlighthouse-report
          path: .unlighthouse
          include-hidden-files: true
          retention-days: 7

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .unlighthouse
          force_orphan: true
